name: artemorfosis
favicon: null
layout_spectrum: 0.8398968009278178
typography_spectrum: 0.32071252283640206
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.1875
  lightness: 0.6740922189783305
  saturation: 0.7557741624768823
  rhythmicContrast: 0.3333624240476638
purpose: []
